import {Inter} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/services/AuthProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "YogaVerse",
  description: "Generated by YogaVerse",
};

export default async function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
